### ISSUE TITLE
Citation 

### ISSUE THREAD

**Issue by alec3010** [jpaine126/Inverted_Pendulum_Control_Demo#7]
I found your code very useful in my Final Thesis. Do you want to be cited? If yes, there is a github tool that allows the author of a repo to be cited: 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by jpaine126** [comment]
I'm sure since I'm a year late to this you already completed your thesis, but thank you anyway for asking. I added an actual license and citation if you ever feel the need to cite this project in the future.
